version: '3.8'

services:
  ed_quant:
    build: .
    container_name: ed_quant
    restart: always
    env_file: .env
    volumes:
      - ./logs:/app/logs
      - ./models:/app/models
      # Important to prevent overwriting paper DB on restart
      - paper_db_volume:/app/paper_db.sqlite3
    environment:
      - TZ=${TZ:-Europe/Istanbul}

volumes:
  paper_db_volume:
