import pandas as pd
import pandas_ta as ta
import numpy as np
from src.logger import get_logger

logger = get_logger("features")

def add_features(df: pd.DataFrame) -> pd.DataFrame:
    """Computes technical indicators and features using vectorized Pandas TA."""
    if df.empty or len(df) < 200:
        logger.warning("DataFrame empty or insufficient length for feature calculation.")
        return df

    # Deep copy to avoid SettingWithCopyWarning
    df_feat = df.copy()

    try:
        # Trend Filters (EMA 50, EMA 200)
        df_feat['EMA_50'] = ta.ema(df_feat['Close'], length=50)
        df_feat['EMA_200'] = ta.ema(df_feat['Close'], length=200)

        # Momentum Oscillators
        df_feat['RSI_14'] = ta.rsi(df_feat['Close'], length=14)

        # MACD (12, 26, 9) returns MACD, Histogram, and Signal
        macd = ta.macd(df_feat['Close'], fast=12, slow=26, signal=9)
        if macd is not None and not macd.empty:
            df_feat['MACD'] = macd['MACD_12_26_9']
            df_feat['MACD_Hist'] = macd['MACDh_12_26_9']
            df_feat['MACD_Signal'] = macd['MACDs_12_26_9']

        # Volatility & Risk Management (ATR, Bollinger Bands)
        df_feat['ATR_14'] = ta.atr(df_feat['High'], df_feat['Low'], df_feat['Close'], length=14)

        bbands = ta.bbands(df_feat['Close'], length=20, std=2)
        if bbands is not None and not bbands.empty:
            df_feat['BB_Lower'] = bbands['BBL_20_2.0']
            df_feat['BB_Upper'] = bbands['BBU_20_2.0']

        # Price Action / Returns
        df_feat['Log_Return'] = np.log(df_feat['Close'] / df_feat['Close'].shift(1))
        df_feat['Pct_Change'] = df_feat['Close'].pct_change()

        # Drop NaN values generated by lookback periods
        df_feat.dropna(inplace=True)

    except Exception as e:
        logger.error(f"Error calculating features: {e}")

    return df_feat

def calculate_z_score(series: pd.Series, window: int = 50) -> pd.Series:
    """Calculates rolling Z-Score to detect flash crash anomalies."""
    rolling_mean = series.rolling(window=window).mean()
    rolling_std = series.rolling(window=window).std()
    return (series - rolling_mean) / rolling_std
