import pandas as pd
import numpy as np
import os
import joblib
from sklearn.ensemble import RandomForestClassifier
from .logger import quant_logger
from .config import MODELS_DIR

class MLValidator:
    def __init__(self, model_name: str = "rf_model.pkl"):
        self.model_path = os.path.join(MODELS_DIR, model_name)
        self.model = self._load_model()

    def _load_model(self) -> RandomForestClassifier:
        if os.path.exists(self.model_path):
            try:
                return joblib.load(self.model_path)
            except Exception as e:
                quant_logger.error(f"Failed to load ML model: {e}")
        return RandomForestClassifier(n_estimators=100, max_depth=5, random_state=42)

    def _create_labels(self, df: pd.DataFrame, forward_periods: int = 5, profit_threshold: float = 0.01) -> pd.DataFrame:
        """
        Creates target labels. 1 if price rises by profit_threshold within forward_periods, else 0.
        """
        # Calculate future return using shift (negative means looking forward)
        df['Future_Return'] = (df['Close'].shift(-forward_periods) - df['Close']) / df['Close']
        df['Target'] = np.where(df['Future_Return'] > profit_threshold, 1, 0)

        # Drop NaN values created by forward shifting
        return df.dropna(subset=['Target'])

    def train_model(self, historical_data_dict: dict):
        """
        Trains the RF model using historical MTF aligned data.
        """
        quant_logger.info("Starting ML Auto-Retraining...")
        X_all, y_all = [], []

        # Determine feature columns safely (dynamically generated by pandas_ta)
        feature_cols = []

        for ticker, df in historical_data_dict.items():
            if df is None or len(df) < 100:
                continue

            df_labeled = self._create_labels(df.copy())

            # Find technical columns (avoiding exact pandas_ta names which vary)
            if not feature_cols:
                feature_cols = [c for c in df_labeled.columns if c not in ['Open', 'High', 'Low', 'Close', 'Volume', 'Future_Return', 'Target'] and 'HTF' not in c]

            if not feature_cols:
                continue

            X_all.append(df_labeled[feature_cols])
            y_all.append(df_labeled['Target'])

        if X_all:
            X = pd.concat(X_all)
            y = pd.concat(y_all)

            try:
                self.model.fit(X, y)
                joblib.dump(self.model, self.model_path)
                quant_logger.info(f"ML Model trained and saved successfully. Features: {len(feature_cols)}")
            except Exception as e:
                quant_logger.error(f"ML training failed: {e}")

    def validate_signal(self, current_features: pd.Series, threshold: float = 0.55) -> bool:
        """
        Validates if the signal has a high probability of success.
        """
        try:
            # Need to reshape Series to DataFrame for sklearn
            feature_df = pd.DataFrame([current_features])

            # Use only columns the model was trained on
            if hasattr(self.model, 'feature_names_in_'):
                missing_cols = set(self.model.feature_names_in_) - set(feature_df.columns)
                for c in missing_cols:
                    feature_df[c] = 0.0 # Fill missing
                feature_df = feature_df[self.model.feature_names_in_]

            prob = self.model.predict_proba(feature_df)[0][1] # Probability of class 1
            if prob >= threshold:
                return True
            else:
                quant_logger.info(f"ML Vetoed signal. Probability: {prob:.2f} < {threshold}")
                return False
        except Exception as e:
            quant_logger.error(f"ML Validation failed: {e}. Passing signal through.")
            return True # Fail-open to allow trading if ML crashes, but log it
