version: '3.8'
services:
  ed_quant_engine:
    build: .
    container_name: ed_quant_engine
    restart: always
    environment:
      - TZ=Europe/Istanbul
    volumes:
      # Veri Kalıcılığı: Konteyner çökse de DB ve Model silinmez!
      - ./paper_db.sqlite3:/app/paper_db.sqlite3
      - ./logs:/app/logs
      - ./rf_model.pkl:/app/rf_model.pkl
      - ./.env:/app/.env:ro
